### ISSUE TITLE
Fix Slack -> IRC mirroring crash on attempting to mirror URLs/images

### ISSUE THREAD

**Issue by jvperrin** [ocf/slackbridge#8]
```
2017-08-16 15:32:25-0700 [-] {'type': 'message', 'channel': 'C02EV1RRE', 'ts': '1502922743.000102', 'hidden': True, 'subtype': 'message_changed', 'message': {'icons': {'image_48': 'https://s3-us-west-2.amazonaws.com/slack-files2/bot_icons/2016-05-25/45780940772_48.png'}, 'attachments': [{'fallback': 'Washington Post: Analysis | Leaving downtown at rush hour in America’s largest cities', 'title': 'Analysis | Leaving downtown at rush hour in America’s largest cities', 'service_name': 'Washington Post', 'image_height': 250, 'image_url': 'https://www.washingtonpost.com/graphics/2017/national/escape-time/img/2300-escape-time_promo.jpg', 'title_link': 'https://www.washingtonpost.com/graphics/2017/national/escape-time/', 'id': 1, 'service_icon': 'http://www.washingtonpost.com/wp-srv/graphics/templates/mobile/ico/apple-touch-icon-144-precomposed.png', 'image_width': 375, 'image_bytes': 355239, 'from_url': 'https://www.washingtonpost.com/graphics/2017/national/escape-time/', 'text': 'Here’s how far you can get f
2017-08-16 15:32:25-0700 [-] Unhandled error in Deferred:
2017-08-16 15:32:25-0700 [-] Unhandled Error
Traceback (most recent call last):
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1199, in run
    self.mainLoop()
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 828, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/slackbridge/slackbridge/bots.py", line 75, in check_slack_rtm
    if user_bot.user_id == message['user']:
builtins.KeyError: 'user'
```

Another example is at https://i.fluffy.cc/xwKkVwSzBFm6WHzXDt6PcGLrpqbbNDwL.html

**Comment by jvperrin** [comment]
This happened again, looks like it happened after an edit to an existing message?

```
2017-08-16 18:02:45-0700 [-] {'title': 'OCF', 'channel': 'C1W5T30SC', 'subtitle': '#test', 'content': 'jvperrin: @waf Currently it’ll require a restart of the bridge until part of https://github.com/ocf/slackbridge/issues/7 is fixed, but you pretty much just create a new Slack channel and it’ll get bridged if you invite the @irc-bridge user', 'launchUri': 'slack://channel?id=C1W5T30SC&message=1502931763000177&team=T02EV1K1G', 'event_ts': '1502931763.000140', 'avatarImage': 'https://secure.gravatar.com/avatar/8cf278828174442a1c7485a2428fa119.jpg?s=192&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0000-192.png', 'imageUri': None, 'type': 'desktop_notification', 'ssbFilename': 'knock_brush.mp3', 'msg': '1502931763.000177', 'is_shared': False}
2017-08-16 18:02:46-0700 [-] {'event_ts': '1502931764.000060', 'channel': 'C1W5T30SC', 'type': 'message', 'previous_message': {'text': '<@U02EV1K1J> Currently it’ll require a restart of the bridge until part of <https://github.com/ocf/slackbridge/issues/7> is fixed, but you pretty much just create a new Slack channel and it’ll get bridged if you invite the <@U1B6FUML3> user', 'ts': '1502931763.000177', 'type': 'message', 'user': 'U0QHZCXST'}, 'message': {'attachments': [{'from_url': 'https://github.com/ocf/slackbridge/issues/7', 'service_name': 'GitHub', 'id': 1, 'title_link': 'https://github.com/ocf/slackbridge/issues/7', 'thumb_height': 250, 'thumb_width': 250, 'thumb_url': 'https://avatars2.githubusercontent.com/u/1523594?v=4&s=400', 'fallback': 'GitHub: Mirror channels more closely · Issue #7 · ocf/slackbridge', 'title': 'Mirror channels more closely · Issue #7 · ocf/slackbridge', 'service_icon': 'https://a.slack-edge.com/bfaba/img/unfurl_icons/github.png'}], 'text': '<@U02EV1K1J> Currently it’l
2017-08-16 18:02:46-0700 [-] Unhandled error in Deferred:
2017-08-16 18:02:46-0700 [-] Unhandled Error
Traceback (most recent call last):
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1199, in run
    self.mainLoop()
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 1208, in mainLoop
    self.runUntilCurrent()
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/base.py", line 828, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/opt/slackbridge/venv/lib/python3.5/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/opt/slackbridge/slackbridge/bots.py", line 75, in check_slack_rtm
    if user_bot.user_id == message['user']:
builtins.KeyError: 'user'
```

**Comment by gnowxilef** [comment]
fwiw, i did not edit the message.

**Comment by jvperrin** [comment]
No, I think I removed the preview though and that counted as an edit, so I think that confused it? Either way, it should just be more resilient and check if the message has a `user` key first so that this doesn't happen.
